from setuptools import find_packages, setup

setup(
    name="async-mojang",
    version="2.0.0",
    author="FroostySnoowman",
    description="An async Python wrapper for the Mojang API.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/FroostySnoowman/Async-Mojang",
    packages=find_packages(),
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Internet",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
        "Typing :: Typed",
    ],
    license="MIT",
    python_requires=">=3.10",
    install_requires=[
        "aiohttp>=3.8,<4",
    ],
    keywords=[
        "mojang",
        "minecraft",
        "api",
        "mojang api",
        "minecraft api",
        "async mojang",
        "async minecraft",
    ],
)
